### ISSUE TITLE
Unable to enter the container as expected

### ISSUE THREAD

**Issue by yowayimono** [lucavallin/barco#5]
Hi ,lucavallin!

I am currently learning your container project and have cloned the code repository. Following your provided examples, I attempted to run the container but encountered an issue. Specifically, when I executed the code as instructed, the container did not enter as expected and exited immediately.

I have made multiple attempts and reviewed the code and relevant configurations, but the problem persists. My assumption is that I might have missed certain steps or configurations, but I am unsure about the specific cause.

My example of running it is like this:

![image](https://github.com/lucavallin/barco/assets/113654403/34220d2c-d8f1-4a74-aedf-40db83e00514)

![image](https://github.com/lucavallin/barco/assets/113654403/54750fc7-f3b5-4b7d-b579-3a0bfa6c2c0f)

My cgroups are already enabled，I hope you can answer this question！

**Comment by yowayimono** [comment]
Here is the detailed output information.
![image](https://github.com/lucavallin/barco/assets/113654403/6ec4587f-e59d-4671-80ec-ceab4de7be61)

**Comment by ghost** [comment]
Seems you are using `zsh`, try ` sudo ./bin/barco -u 0 -m / -c $(which zsh)`

**Comment by yowayimono** [comment]
The problem is solved, and this project is fantastic! Thank you for your assistance.

**Comment by lucavallin** [comment]
@yowayimono Thanks for reporting the issue and glad to hear the problem is fixed and that you enjoy the project. @swordli-dev thanks for the quick help provided!
